export const siteConfig = {
  name: 'Multi New Trends',
  shortName: 'MNT',
  tagline: 'Everything You Need. One Trend Away.',
  description:
    'Multi New Trends is a multi-category shopping and hyperlocal commerce platform connecting customers with products, local vendors, and delivery partners.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://multinewtrends.com',
  ogImage: '/assets/hero.png',
  logo: '/assets/logo/logo.png',
  phone: '+91 9992125566',
  email: 'support@multinewtrends.com',
  themeColor: '#FA4C00',
  colors: {
    primary: '#FA4C00',
    secondary: '#FFBD59',
    background: '#FAF4E6',
    dark: '#090909',
  },
  socials: {
    facebook: 'https://www.facebook.com/Multinewtrends/',
    instagram: 'https://www.instagram.com/multinewtrends',
    twitter: 'https://x.com/MultinewTrends',
    linkedin: 'https://www.linkedin.com/in/multinewtrends/',
    youtube: 'https://www.youtube.com/@multinewtrends',
  },
  categories: [
    'Grocery',
    'Electronics',
    'Home Living',
    'Kitchen',
    'Kids',
    'Sports',
    'Stationery & Books',
    'Pet Products',
    'Gifts',
    'Mobile Accessories',
    'Beauty',
    'Fashion',
  ],
};
